export enum TODO_ACTION {
  SET_TODO_LIST = "SET_TODO_LIST",
  UNSET_TODO_LIST = "UNSET_TODO_LIST",
  SET_TODO = "SET_TODO",
  UNSET_TODO = "UNSET_TODO",
}

export enum BUCKET_ACTION {
  SET_BUCKET_LIST = "SET_BUCKET_LIST",
  UNSET_BUCKET_LIST = "UNSET_BUCKET_LIST",
  SET_BUCKET = "SET_BUCKET",
  UNSET_BUCKET = "UNSET_BUCKET",
}


export enum AUTH_ACTION {
  SET_AUTH = 'SET_AUTH',
  UNSET_AUTH = 'UNSET_AUTH'
}
